version: "3.8"

services:
  client:
    build:
      context: .
    container_name: client
    ports:
      - "3000:3000"
    restart: always
    image: ivantom/tp-blog-client
    networks:
      - blog

networks:
  blog:
