apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: client
build:
  artifacts:
    - image: ivantom/tp-blog-client
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s/deployment.yaml
    - k8s/ingress.yaml
    - k8s/nodeport.yaml
    - k8s/service.yaml
