apiVersion: v1
kind: Service
metadata:
  name: client-nodeport
spec:
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31000
  type: NodePort
  