version: "3.8"

services:
  event-bus-service:
    build:
      context: .
    ports:
      - "4005:4005"
    container_name: event_bus
    restart: always
    image: ivantom/tp-blog-event-bus
    networks:
      - blog

networks:
  blog:
    