version: "3.8"

services:
  event_bus:
    build:
      context: .
    ports:
      - "4005:4005"
    container_name: event_bus
    restart: always
    image: tp-block/event-bus:latest
    networks:
      - blog

networks:
  blog:
    