apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-deployment
  labels:
    app: posts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      name: posts
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: ivantom/tp-blog-posts
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
      restartPolicy: Always
      