apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderation-deployment
  labels:
    app: moderation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moderation
  template:
    metadata:
      name: moderation
      labels:
        app: moderation
    spec:
      containers:
        - name: moderation
          image: ivantom/tp-blog-moderation
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort : 4003
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
      restartPolicy: Always
      