version: "3.8"

services:
  comments:
    build:
      context: .
    ports:
      - "4001:4001"
    container_name: comments
    restart: always
    image: ivantom/tp-blog-comments
    networks:
      - blog

networks:
  blog:
    