version: "3.8"

services:
  moderation-service:
    build:
      context: .
    ports:
      - "4003:4003"
    container_name: moderation
    restart: always
    image: ivantom/tp-blog-moderation
    networks:
      - blog

networks:
  blog:
    