apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: moderation
build:
  artifacts:
    - image: ivantom/tp-blog-moderation
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s/deployment.yaml
    - k8s/service.yaml
