apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-bus-deployment
  labels:
    app: event-bus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-bus
  template:
    metadata:
      name: event-bus
      labels:
        app: event-bus
    spec:
      containers:
        - name: event-bus
          image: ivantom/tp-blog-event-bus
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort : 4005
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
      restartPolicy: Always
      