version: "3.8"

services:
  query:
    build:
      context: .
    ports:
      - "4002:4002"
    container_name: query
    restart: always
    image: ivantom/tp-blog-query
    networks:
      - blog

networks:
  blog:
