apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-deployment
  labels:
    app: comments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comments
  template:
    metadata:
      name: comments-pod
      labels:
        app: comments
    spec:
      containers:
        - name: comments
          image: ivantom/tp-blog-comments
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort : 4001
      restartPolicy: Always
      