version: "3.8"

services:
  posts:
    build:
      context: .
    ports:
      - "4003:4003"
    container_name: posts
    restart: always
    image: tp-blog/posts:latest
    networks:
      - blog

networks:
  blog:
