version: "3.8"

services:
  post-service:
    build:
      context: .
    ports:
      - "4000:4000"
    container_name: posts
    restart: always
    image: ivantom/tp-blog-posts
    networks:
      - blog

networks:
  blog:
