apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: posts
build:
  artifacts:
    - image: ivantom/tp-blog-posts
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s/deployment.yaml
    - k8s/service.yaml
