apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-deployment
  labels:
    app: query
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query
  template:
    metadata:
      name: query-pod
      labels:
        app: query
    spec:
      containers:
        - name: query
          image: ivantom/tp-blog-query
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4001
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
      restartPolicy: Always
      