apiVersion: v1
kind: Service
metadata:
  name: query-service
spec:
  selector:
    app: query
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 80
      nodePort: 4001
  type: LoadBalancer
  